In [108]:
from scipy import signal
import numpy as np

In [109]:
#kernel = np.array([[0,0,0],[0,1,0],[0,0,0]],dtype=np.float32)
kernel = np.random.rand(3,3).astype(np.float16)

In [96]:
kernel

array([[0.11896, 0.8145 , 0.5425 ],
       [0.4412 , 0.02057, 0.531  ],
       [0.0727 , 0.7515 , 0.676  ]], dtype=float16)

In [104]:
matrix = np.random.rand(128,128) #.astype(np.float16)

In [105]:
matrix

array([[0.48591361, 0.27752433, 0.57599314, ..., 0.83593427, 0.03800617,
        0.23372718],
       [0.15470032, 0.80676146, 0.05820667, ..., 0.8677902 , 0.6233346 ,
        0.40697681],
       [0.35926966, 0.51516942, 0.09751553, ..., 0.3752119 , 0.90364348,
        0.25188864],
       ...,
       [0.31113635, 0.2124242 , 0.48463509, ..., 0.09923498, 0.98480636,
        0.06854667],
       [0.45173474, 0.3118311 , 0.57813568, ..., 0.03255168, 0.52269768,
        0.48821536],
       [0.44654672, 0.57549304, 0.2057586 , ..., 0.75993817, 0.59628993,
        0.69220595]])

In [107]:
%time signal.convolve2d(matrix,kernel,boundary='wrap', mode='valid')

CPU times: user 1.02 ms, sys: 0 ns, total: 1.02 ms
Wall time: 903 µs


array([[1.32925174, 1.85454951, 1.66402857, ..., 2.38247801, 2.384499  ,
        2.23289758],
       [2.20729572, 2.0912672 , 1.25034121, ..., 1.31090411, 1.97095578,
        2.06406083],
       [2.09219119, 2.06421643, 2.05762311, ..., 1.44653259, 1.97913463,
        2.56365158],
       ...,
       [1.2842088 , 2.05623983, 2.26985817, ..., 2.17038859, 1.42562581,
        1.61613516],
       [1.85960787, 2.39793323, 2.47988589, ..., 2.2365925 , 2.05178585,
        1.16561791],
       [1.64177953, 1.61667476, 2.00445071, ..., 2.67541047, 2.35006146,
        2.03574686]])